apiVersion: v1
kind: ServiceAccount
metadata:
  name: qa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: qa-role
rules:
 - apiGroups: ["*"]
   resources: ["pods"]
   verbs: ["list","get","watch"]
 - apiGroups: ["extensions","apps"]
   resources: ["deployments"]
   verbs: ["get","list","watch", "create", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: qa-pods
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: qa
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: qa-role